---

- debug:
    msg: "******************** CUSTOM PRE [START] *******************"

- name: "Add ssh.github.com as a known host"
  lineinfile:
    dest: /{{ plone_target_path }}/.ssh/known_hosts
    create: yes
    state: present
    owner: senaite
    group: senaite
    line: "{{ lookup('pipe', 'ssh-keyscan -H -t rsa -p 443 ssh.github.com') }}"
    regexp: "^ssh\\.github\\.com"
  tags:
    - senaite-custom

- name: "Generate SSH key"
  user:
    name: "{{user}}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: "{{ plone_target_path }}/.ssh/{{ ssh_key_filename }}"

- name: "Check SSH public key"
  command: "cat {{ plone_target_path }}/.ssh/{{ ssh_key_filename }}.pub"
  register: cat
  changed_when: False

- name: "Print SSH public key"
  debug:
    var: cat.stdout

- name: "Wait for user to copy SSH public key"
  pause:
    prompt: "Please, add the SSH public key above to the GitHub account ..."

- name: "Configure Secure Access to remote source repos"
  template:
    src: templates/ssh_config.conf.j2
    dest: "{{ plone_target_path }}/.ssh/config"
    force: no
    owner: senaite
    group: senaite
    mode: 0600
  tags:
    - senaite-custom

- name: "Add SWAP configuration"
  template:
    src: templates/90-senaite-sysctl.conf.j2
    dest: "/etc/sysctl.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - senaite-custom

- debug:
    msg: "******************** CUSTOM PRE [DONE] ********************"
